/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingId = IDL.Nat;
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const BookingDetails = IDL.Record({
  'dropoff' : IDL.Text,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'time' : IDL.Text,
  'pickup' : IDL.Text,
  'notes' : IDL.Text,
  'vehicle' : IDL.Text,
  'phone' : IDL.Text,
});
export const BookingRecord = IDL.Record({
  'id' : BookingId,
  'status' : BookingStatus,
  'createdAt' : IDL.Int,
  'details' : BookingDetails,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBooking' : IDL.Func([BookingId], [IDL.Bool], []),
  'getAllBookingsForAdmin' : IDL.Func([], [IDL.Vec(BookingRecord)], ['query']),
  'getBookingStatusById' : IDL.Func(
      [BookingId],
      [IDL.Opt(BookingStatus)],
      ['query'],
    ),
  'getBookingsByPhone' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BookingRecord)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserIdByName' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Principal)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitBooking' : IDL.Func([BookingDetails], [BookingId], []),
  'updateBookingStatus' : IDL.Func([BookingId, BookingStatus], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingId = IDL.Nat;
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const BookingDetails = IDL.Record({
    'dropoff' : IDL.Text,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'time' : IDL.Text,
    'pickup' : IDL.Text,
    'notes' : IDL.Text,
    'vehicle' : IDL.Text,
    'phone' : IDL.Text,
  });
  const BookingRecord = IDL.Record({
    'id' : BookingId,
    'status' : BookingStatus,
    'createdAt' : IDL.Int,
    'details' : BookingDetails,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBooking' : IDL.Func([BookingId], [IDL.Bool], []),
    'getAllBookingsForAdmin' : IDL.Func(
        [],
        [IDL.Vec(BookingRecord)],
        ['query'],
      ),
    'getBookingStatusById' : IDL.Func(
        [BookingId],
        [IDL.Opt(BookingStatus)],
        ['query'],
      ),
    'getBookingsByPhone' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BookingRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserIdByName' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitBooking' : IDL.Func([BookingDetails], [BookingId], []),
    'updateBookingStatus' : IDL.Func(
        [BookingId, BookingStatus],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };